declare namespace ACTIONS {
    type WINDOW_FOCUSED = 'WINDOW_FOCUSED';
    type DAEMON_READY = 'DAEMON_READY';
    type DAEMON_VERSION_MATCH = 'DAEMON_VERSION_MATCH';
    type DAEMON_VERSION_MISMATCH = 'DAEMON_VERSION_MISMATCH';
    type VOLUME_CHANGED = 'VOLUME_CHANGED';
    type SET_WELCOME_VERSION = 'SET_WELCOME_VERSION';
    type SET_ALLOW_ANALYTICS = 'SET_ALLOW_ANALYTICS';
    
    // Navigation
    type CHANGE_AFTER_AUTH_PATH = 'CHANGE_AFTER_AUTH_PATH';
    type WINDOW_SCROLLED = 'WINDOW_SCROLLED';
    type HISTORY_NAVIGATE = 'HISTORY_NAVIGATE';
    
    // Upgrades
    type UPGRADE_CANCELLED = 'UPGRADE_CANCELLED';
    type DOWNLOAD_UPGRADE = 'DOWNLOAD_UPGRADE';
    type UPGRADE_DOWNLOAD_STARTED = 'UPGRADE_DOWNLOAD_STARTED';
    type UPGRADE_DOWNLOAD_COMPLETED = 'UPGRADE_DOWNLOAD_COMPLETED';
    type UPGRADE_DOWNLOAD_PROGRESSED = 'UPGRADE_DOWNLOAD_PROGRESSED';
    type CHECK_UPGRADE_AVAILABLE = 'CHECK_UPGRADE_AVAILABLE';
    type CHECK_UPGRADE_START = 'CHECK_UPGRADE_START';
    type CHECK_UPGRADE_SUCCESS = 'CHECK_UPGRADE_SUCCESS';
    type CHECK_UPGRADE_FAIL = 'CHECK_UPGRADE_FAIL';
    type CHECK_UPGRADE_SUBSCRIBE = 'CHECK_UPGRADE_SUBSCRIBE';
    type UPDATE_VERSION = 'UPDATE_VERSION';
    type UPDATE_REMOTE_VERSION = 'UPDATE_REMOTE_VERSION';
    type SKIP_UPGRADE = 'SKIP_UPGRADE';
    type START_UPGRADE = 'START_UPGRADE';
    type AUTO_UPDATE_DECLINED = 'AUTO_UPDATE_DECLINED';
    type AUTO_UPDATE_DOWNLOADED = 'AUTO_UPDATE_DOWNLOADED';
    type CLEAR_UPGRADE_TIMER = 'CLEAR_UPGRADE_TIMER';
    
    // Wallet
    type GET_NEW_ADDRESS_STARTED = 'GET_NEW_ADDRESS_STARTED';
    type GET_NEW_ADDRESS_COMPLETED = 'GET_NEW_ADDRESS_COMPLETED';
    type FETCH_TRANSACTIONS_STARTED = 'FETCH_TRANSACTIONS_STARTED';
    type FETCH_TRANSACTIONS_COMPLETED = 'FETCH_TRANSACTIONS_COMPLETED';
    type FETCH_TXO_PAGE_STARTED = 'FETCH_TXO_PAGE_STARTED';
    type FETCH_TXO_PAGE_COMPLETED = 'FETCH_TXO_PAGE_COMPLETED';
    type FETCH_TXO_PAGE_FAILED = 'FETCH_TXO_PAGE_FAILED';
    type UPDATE_TXO_FETCH_PARAMS = 'UPDATE_TXO_FETCH_PARAMS';
    type FETCH_SUPPORTS_STARTED = 'FETCH_SUPPORTS_STARTED';
    type FETCH_SUPPORTS_COMPLETED = 'FETCH_SUPPORTS_COMPLETED';
    type ABANDON_SUPPORT_STARTED = 'ABANDON_SUPPORT_STARTED';
    type ABANDON_SUPPORT_COMPLETED = 'ABANDON_SUPPORT_COMPLETED';
    type ABANDON_CLAIM_SUPPORT_STARTED = 'ABANDON_CLAIM_SUPPORT_STARTED';
    type ABANDON_CLAIM_SUPPORT_COMPLETED = 'ABANDON_CLAIM_SUPPORT_COMPLETED';
    type ABANDON_CLAIM_SUPPORT_FAILED = 'ABANDON_CLAIM_SUPPORT_FAILED';
    type ABANDON_CLAIM_SUPPORT_PREVIEW = 'ABANDON_CLAIM_SUPPORT_PREVIEW';
    type PENDING_SUPPORTS_UPDATED = 'PENDING_SUPPORTS_UPDATED';
    type UPDATE_BALANCE = 'UPDATE_BALANCE';
    type UPDATE_TOTAL_BALANCE = 'UPDATE_TOTAL_BALANCE';
    type CHECK_ADDRESS_IS_MINE_STARTED = 'CHECK_ADDRESS_IS_MINE_STARTED';
    type CHECK_ADDRESS_IS_MINE_COMPLETED = 'CHECK_ADDRESS_IS_MINE_COMPLETED';
    type SEND_TRANSACTION_STARTED = 'SEND_TRANSACTION_STARTED';
    type SEND_TRANSACTION_COMPLETED = 'SEND_TRANSACTION_COMPLETED';
    type SEND_TRANSACTION_FAILED = 'SEND_TRANSACTION_FAILED';
    type SUPPORT_TRANSACTION_STARTED = 'SUPPORT_TRANSACTION_STARTED';
    type SUPPORT_TRANSACTION_COMPLETED = 'SUPPORT_TRANSACTION_COMPLETED';
    type SUPPORT_TRANSACTION_FAILED = 'SUPPORT_TRANSACTION_FAILED';
    type CLEAR_SUPPORT_TRANSACTION = 'CLEAR_SUPPORT_TRANSACTION';
    type WALLET_ENCRYPT_START = 'WALLET_ENCRYPT_START';
    type WALLET_ENCRYPT_COMPLETED = 'WALLET_ENCRYPT_COMPLETED';
    type WALLET_ENCRYPT_FAILED = 'WALLET_ENCRYPT_FAILED';
    type WALLET_UNLOCK_START = 'WALLET_UNLOCK_START';
    type WALLET_UNLOCK_COMPLETED = 'WALLET_UNLOCK_COMPLETED';
    type WALLET_UNLOCK_FAILED = 'WALLET_UNLOCK_FAILED';
    type WALLET_DECRYPT_START = 'WALLET_DECRYPT_START';
    type WALLET_DECRYPT_COMPLETED = 'WALLET_DECRYPT_COMPLETED';
    type WALLET_DECRYPT_FAILED = 'WALLET_DECRYPT_FAILED';
    type WALLET_LOCK_START = 'WALLET_LOCK_START';
    type WALLET_LOCK_COMPLETED = 'WALLET_LOCK_COMPLETED';
    type WALLET_LOCK_FAILED = 'WALLET_LOCK_FAILED';
    type WALLET_STATUS_START = 'WALLET_STATUS_START';
    type WALLET_STATUS_COMPLETED = 'WALLET_STATUS_COMPLETED';
    type WALLET_RESTART = 'WALLET_RESTART';
    type WALLET_RESTART_COMPLETED = 'WALLET_RESTART_COMPLETED';
    type SET_TRANSACTION_LIST_FILTER = 'SET_TRANSACTION_LIST_FILTER';
    type UPDATE_CURRENT_HEIGHT = 'UPDATE_CURRENT_HEIGHT';
    type SET_DRAFT_TRANSACTION_AMOUNT = 'SET_DRAFT_TRANSACTION_AMOUNT';
    type SET_DRAFT_TRANSACTION_ADDRESS = 'SET_DRAFT_TRANSACTION_ADDRESS';
    type FETCH_UTXO_COUNT_STARTED = 'FETCH_UTXO_COUNT_STARTED';
    type FETCH_UTXO_COUNT_COMPLETED = 'FETCH_UTXO_COUNT_COMPLETED';
    type FETCH_UTXO_COUNT_FAILED = 'FETCH_UTXO_COUNT_FAILED';
    type TIP_CLAIM_MASS_STARTED = 'TIP_CLAIM_MASS_STARTED';
    type TIP_CLAIM_MASS_COMPLETED = 'TIP_CLAIM_MASS_COMPLETED';
    type TIP_CLAIM_MASS_FAILED = 'TIP_CLAIM_MASS_FAILED';
    type DO_UTXO_CONSOLIDATE_STARTED = 'DO_UTXO_CONSOLIDATE_STARTED';
    type DO_UTXO_CONSOLIDATE_COMPLETED = 'DO_UTXO_CONSOLIDATE_COMPLETED';
    type DO_UTXO_CONSOLIDATE_FAILED = 'DO_UTXO_CONSOLIDATE_FAILED';
    type PENDING_CONSOLIDATED_TXOS_UPDATED = 'PENDING_CONSOLIDATED_TXOS_UPDATED';
    
    // Claims
    type RESOLVE_URIS_STARTED = 'RESOLVE_URIS_STARTED';
    type RESOLVE_URIS_COMPLETED = 'RESOLVE_URIS_COMPLETED';
    type FETCH_CHANNEL_CLAIMS_STARTED = 'FETCH_CHANNEL_CLAIMS_STARTED';
    type FETCH_CHANNEL_CLAIMS_COMPLETED = 'FETCH_CHANNEL_CLAIMS_COMPLETED';
    type FETCH_CLAIM_LIST_MINE_STARTED = 'FETCH_CLAIM_LIST_MINE_STARTED';
    type FETCH_CLAIM_LIST_MINE_COMPLETED = 'FETCH_CLAIM_LIST_MINE_COMPLETED';
    type ABANDON_CLAIM_STARTED = 'ABANDON_CLAIM_STARTED';
    type ABANDON_CLAIM_SUCCEEDED = 'ABANDON_CLAIM_SUCCEEDED';
    type FETCH_CHANNEL_LIST_STARTED = 'FETCH_CHANNEL_LIST_STARTED';
    type FETCH_CHANNEL_LIST_COMPLETED = 'FETCH_CHANNEL_LIST_COMPLETED';
    type FETCH_CHANNEL_LIST_FAILED = 'FETCH_CHANNEL_LIST_FAILED';
    type CREATE_CHANNEL_STARTED = 'CREATE_CHANNEL_STARTED';
    type CREATE_CHANNEL_COMPLETED = 'CREATE_CHANNEL_COMPLETED';
    type CREATE_CHANNEL_FAILED = 'CREATE_CHANNEL_FAILED';
    type UPDATE_CHANNEL_STARTED = 'UPDATE_CHANNEL_STARTED';
    type UPDATE_CHANNEL_COMPLETED = 'UPDATE_CHANNEL_COMPLETED';
    type UPDATE_CHANNEL_FAILED = 'UPDATE_CHANNEL_FAILED';
    type IMPORT_CHANNEL_STARTED = 'IMPORT_CHANNEL_STARTED';
    type IMPORT_CHANNEL_COMPLETED = 'IMPORT_CHANNEL_COMPLETED';
    type IMPORT_CHANNEL_FAILED = 'IMPORT_CHANNEL_FAILED';
    type PUBLISH_STARTED = 'PUBLISH_STARTED';
    type PUBLISH_COMPLETED = 'PUBLISH_COMPLETED';
    type PUBLISH_FAILED = 'PUBLISH_FAILED';
    type SET_PLAYING_URI = 'SET_PLAYING_URI';
    type SET_CONTENT_POSITION = 'SET_CONTENT_POSITION';
    type SET_CONTENT_LAST_VIEWED = 'SET_CONTENT_LAST_VIEWED';
    type CLEAR_CONTENT_HISTORY_URI = 'CLEAR_CONTENT_HISTORY_URI';
    type CLEAR_CONTENT_HISTORY_ALL = 'CLEAR_CONTENT_HISTORY_ALL';
    type CLAIM_SEARCH_STARTED = 'CLAIM_SEARCH_STARTED';
    type CLAIM_SEARCH_COMPLETED = 'CLAIM_SEARCH_COMPLETED';
    type CLAIM_SEARCH_FAILED = 'CLAIM_SEARCH_FAILED';
    type CLAIM_SEARCH_BY_TAGS_STARTED = 'CLAIM_SEARCH_BY_TAGS_STARTED';
    type CLAIM_SEARCH_BY_TAGS_COMPLETED = 'CLAIM_SEARCH_BY_TAGS_COMPLETED';
    type CLAIM_SEARCH_BY_TAGS_FAILED = 'CLAIM_SEARCH_BY_TAGS_FAILED';
    type CLAIM_REPOST_STARTED = 'CLAIM_REPOST_STARTED';
    type CLAIM_REPOST_COMPLETED = 'CLAIM_REPOST_COMPLETED';
    type CLAIM_REPOST_FAILED = 'CLAIM_REPOST_FAILED';
    type CLEAR_REPOST_ERROR = 'CLEAR_REPOST_ERROR';
    type CLEAR_CHANNEL_ERRORS = 'CLEAR_CHANNEL_ERRORS';
    type CHECK_PUBLISH_NAME_STARTED = 'CHECK_PUBLISH_NAME_STARTED';
    type CHECK_PUBLISH_NAME_COMPLETED = 'CHECK_PUBLISH_NAME_COMPLETED';
    type UPDATE_PENDING_CLAIMS = 'UPDATE_PENDING_CLAIMS';
    type UPDATE_CONFIRMED_CLAIMS = 'UPDATE_CONFIRMED_CLAIMS';
    type ADD_FILES_REFLECTING = 'ADD_FILES_REFLECTING';
    type UPDATE_FILES_REFLECTING = 'UPDATE_FILES_REFLECTING';
    type TOGGLE_CHECKING_REFLECTING = 'TOGGLE_CHECKING_REFLECTING';
    type TOGGLE_CHECKING_PENDING = 'TOGGLE_CHECKING_PENDING';
    type PURCHASE_LIST_STARTED = 'PURCHASE_LIST_STARTED';
    type PURCHASE_LIST_COMPLETED = 'PURCHASE_LIST_COMPLETED';
    type PURCHASE_LIST_FAILED = 'PURCHASE_LIST_FAILED';
    
    // Comments
    type COMMENT_LIST_STARTED = 'COMMENT_LIST_STARTED';
    type COMMENT_LIST_COMPLETED = 'COMMENT_LIST_COMPLETED';
    type COMMENT_LIST_FAILED = 'COMMENT_LIST_FAILED';
    type COMMENT_CREATE_STARTED = 'COMMENT_CREATE_STARTED';
    type COMMENT_CREATE_COMPLETED = 'COMMENT_CREATE_COMPLETED';
    type COMMENT_CREATE_FAILED = 'COMMENT_CREATE_FAILED';
    type COMMENT_ABANDON_STARTED = 'COMMENT_ABANDON_STARTED';
    type COMMENT_ABANDON_COMPLETED = 'COMMENT_ABANDON_COMPLETED';
    type COMMENT_ABANDON_FAILED = 'COMMENT_ABANDON_FAILED';
    type COMMENT_UPDATE_STARTED = 'COMMENT_UPDATE_STARTED';
    type COMMENT_UPDATE_COMPLETED = 'COMMENT_UPDATE_COMPLETED';
    type COMMENT_UPDATE_FAILED = 'COMMENT_UPDATE_FAILED';
    type COMMENT_HIDE_STARTED = 'COMMENT_HIDE_STARTED';
    type COMMENT_HIDE_COMPLETED = 'COMMENT_HIDE_COMPLETED';
    type COMMENT_HIDE_FAILED = 'COMMENT_HIDE_FAILED';
    
    // Files
    type FILE_LIST_STARTED = 'FILE_LIST_STARTED';
    type FILE_LIST_SUCCEEDED = 'FILE_LIST_SUCCEEDED';
    type FETCH_FILE_INFO_STARTED = 'FETCH_FILE_INFO_STARTED';
    type FETCH_FILE_INFO_COMPLETED = 'FETCH_FILE_INFO_COMPLETED';
    type FETCH_FILE_INFO_FAILED = 'FETCH_FILE_INFO_FAILED';
    type LOADING_VIDEO_STARTED = 'LOADING_VIDEO_STARTED';
    type LOADING_VIDEO_COMPLETED = 'LOADING_VIDEO_COMPLETED';
    type LOADING_VIDEO_FAILED = 'LOADING_VIDEO_FAILED';
    type DOWNLOADING_STARTED = 'DOWNLOADING_STARTED';
    type DOWNLOADING_PROGRESSED = 'DOWNLOADING_PROGRESSED';
    type DOWNLOADING_COMPLETED = 'DOWNLOADING_COMPLETED';
    type DOWNLOADING_CANCELED = 'DOWNLOADING_CANCELED';
    type PLAY_VIDEO_STARTED = 'PLAY_VIDEO_STARTED';
    type FETCH_AVAILABILITY_STARTED = 'FETCH_AVAILABILITY_STARTED';
    type FETCH_AVAILABILITY_COMPLETED = 'FETCH_AVAILABILITY_COMPLETED';
    type FILE_DELETE = 'FILE_DELETE';
    type SET_FILE_LIST_SORT = 'SET_FILE_LIST_SORT';
    type PURCHASE_URI_STARTED = 'PURCHASE_URI_STARTED';
    export type PURCHASE_URI_COMPLETED = 'PURCHASE_URI_COMPLETED';
    type PURCHASE_URI_FAILED = 'PURCHASE_URI_FAILED';
    type CLEAR_PURCHASED_URI_SUCCESS = 'CLEAR_PURCHASED_URI_SUCCESS';
    
    // Settings
    type DAEMON_SETTINGS_RECEIVED = 'DAEMON_SETTINGS_RECEIVED';
    type DAEMON_STATUS_RECEIVED = 'DAEMON_STATUS_RECEIVED';
    type SHARED_PREFERENCE_SET = 'SHARED_PREFERENCE_SET';
    type SAVE_CUSTOM_WALLET_SERVERS = 'SAVE_CUSTOM_WALLET_SERVERS';
    type CLIENT_SETTING_CHANGED = 'CLIENT_SETTING_CHANGED';
    type UPDATE_IS_NIGHT = 'UPDATE_IS_NIGHT';
    
    // User
    type AUTHENTICATION_STARTED = 'AUTHENTICATION_STARTED';
    type AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
    type AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
    type USER_EMAIL_DECLINE = 'USER_EMAIL_DECLINE';
    type USER_EMAIL_NEW_STARTED = 'USER_EMAIL_NEW_STARTED';
    type USER_EMAIL_NEW_SUCCESS = 'USER_EMAIL_NEW_SUCCESS';
    type USER_EMAIL_NEW_EXISTS = 'USER_EMAIL_NEW_EXISTS';
    type USER_EMAIL_NEW_FAILURE = 'USER_EMAIL_NEW_FAILURE';
    type USER_EMAIL_VERIFY_SET = 'USER_EMAIL_VERIFY_SET';
    type USER_EMAIL_VERIFY_STARTED = 'USER_EMAIL_VERIFY_STARTED';
    type USER_EMAIL_VERIFY_SUCCESS = 'USER_EMAIL_VERIFY_SUCCESS';
    type USER_EMAIL_VERIFY_FAILURE = 'USER_EMAIL_VERIFY_FAILURE';
    type USER_EMAIL_VERIFY_RETRY = 'USER_EMAIL_VERIFY_RETRY';
    type USER_PHONE_RESET = 'USER_PHONE_RESET';
    type USER_PHONE_NEW_STARTED = 'USER_PHONE_NEW_STARTED';
    type USER_PHONE_NEW_SUCCESS = 'USER_PHONE_NEW_SUCCESS';
    type USER_PHONE_NEW_FAILURE = 'USER_PHONE_NEW_FAILURE';
    type USER_PHONE_VERIFY_STARTED = 'USER_PHONE_VERIFY_STARTED';
    type USER_PHONE_VERIFY_SUCCESS = 'USER_PHONE_VERIFY_SUCCESS';
    type USER_PHONE_VERIFY_FAILURE = 'USER_PHONE_VERIFY_FAILURE';
    type USER_IDENTITY_VERIFY_STARTED = 'USER_IDENTITY_VERIFY_STARTED';
    type USER_IDENTITY_VERIFY_SUCCESS = 'USER_IDENTITY_VERIFY_SUCCESS';
    type USER_IDENTITY_VERIFY_FAILURE = 'USER_IDENTITY_VERIFY_FAILURE';
    type USER_FETCH_STARTED = 'USER_FETCH_STARTED';
    type USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
    type USER_FETCH_FAILURE = 'USER_FETCH_FAILURE';
    type USER_INVITE_STATUS_FETCH_STARTED = 'USER_INVITE_STATUS_FETCH_STARTED';
    type USER_INVITE_STATUS_FETCH_SUCCESS = 'USER_INVITE_STATUS_FETCH_SUCCESS';
    type USER_INVITE_STATUS_FETCH_FAILURE = 'USER_INVITE_STATUS_FETCH_FAILURE';
    type USER_INVITE_NEW_STARTED = 'USER_INVITE_NEW_STARTED';
    type USER_INVITE_NEW_SUCCESS = 'USER_INVITE_NEW_SUCCESS';
    type USER_INVITE_NEW_FAILURE = 'USER_INVITE_NEW_FAILURE';
    type FETCH_ACCESS_TOKEN_SUCCESS = 'FETCH_ACCESS_TOKEN_SUCCESS';
    
    // Rewards
    type FETCH_REWARDS_STARTED = 'FETCH_REWARDS_STARTED';
    type FETCH_REWARDS_COMPLETED = 'FETCH_REWARDS_COMPLETED';
    type CLAIM_REWARD_STARTED = 'CLAIM_REWARD_STARTED';
    type CLAIM_REWARD_SUCCESS = 'CLAIM_REWARD_SUCCESS';
    type CLAIM_REWARD_FAILURE = 'CLAIM_REWARD_FAILURE';
    type CLAIM_REWARD_CLEAR_ERROR = 'CLAIM_REWARD_CLEAR_ERROR';
    type FETCH_REWARD_CONTENT_COMPLETED = 'FETCH_REWARD_CONTENT_COMPLETED';
    
    // Language
    type DOWNLOAD_LANGUAGE_SUCCEEDED = 'DOWNLOAD_LANGUAGE_SUCCEEDED';
    type DOWNLOAD_LANGUAGE_FAILED = 'DOWNLOAD_LANGUAGE_FAILED';
    
    // Subscriptions
    type CHANNEL_SUBSCRIBE = 'CHANNEL_SUBSCRIBE';
    type CHANNEL_UNSUBSCRIBE = 'CHANNEL_UNSUBSCRIBE';
    type HAS_FETCHED_SUBSCRIPTIONS = 'HAS_FETCHED_SUBSCRIPTIONS';
    type SET_SUBSCRIPTION_LATEST = 'SET_SUBSCRIPTION_LATEST';
    type SET_SUBSCRIPTION_NOTIFICATION = 'SET_SUBSCRIPTION_NOTIFICATION';
    type SET_SUBSCRIPTION_NOTIFICATIONS = 'SET_SUBSCRIPTION_NOTIFICATIONS';
    type CHECK_SUBSCRIPTION_STARTED = 'CHECK_SUBSCRIPTION_STARTED';
    type CHECK_SUBSCRIPTION_COMPLETED = 'CHECK_SUBSCRIPTION_COMPLETED';
    type CHECK_SUBSCRIPTIONS_SUBSCRIBE = 'CHECK_SUBSCRIPTIONS_SUBSCRIBE';
    
    // Publishing
    type CLEAR_PUBLISH = 'CLEAR_PUBLISH';
    type UPDATE_PUBLISH_FORM = 'UPDATE_PUBLISH_FORM';
    type PUBLISH_START = 'PUBLISH_START';
    type PUBLISH_SUCCESS = 'PUBLISH_SUCCESS';
    type PUBLISH_FAIL = 'PUBLISH_FAIL';
    type CLEAR_PUBLISH_ERROR = 'CLEAR_PUBLISH_ERROR';
    type REMOVE_PENDING_PUBLISH = 'REMOVE_PENDING_PUBLISH';
    type DO_PREPARE_EDIT = 'DO_PREPARE_EDIT';
    
    // Notifications
    type CREATE_NOTIFICATION = 'CREATE_NOTIFICATION';
    type EDIT_NOTIFICATION = 'EDIT_NOTIFICATION';
    type DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
    type DISMISS_NOTIFICATION = 'DISMISS_NOTIFICATION';
    type CREATE_TOAST = 'CREATE_TOAST';
    type DISMISS_TOAST = 'DISMISS_TOAST';
    type CREATE_ERROR = 'CREATE_ERROR';
    type DISMISS_ERROR = 'DISMISS_ERROR';
    
    type FETCH_DATE = 'FETCH_DATE';
    
    // Cost info
    type FETCH_COST_INFO_STARTED = 'FETCH_COST_INFO_STARTED';
    type FETCH_COST_INFO_COMPLETED = 'FETCH_COST_INFO_COMPLETED';
    type FETCH_COST_INFO_FAILED = 'FETCH_COST_INFO_FAILED';
    
    // Sync
    type USER_STATE_POPULATE = 'USER_STATE_POPULATE';
    type SYNC_FATAL_ERROR = 'SYNC_FATAL_ERROR';
}
