declare namespace PAGES {
    const AUTH = 'auth';
    const BACKUP = 'backup';
    const CHANNEL = 'channel';
    const DISCOVER = 'discover';
    const FILE = 'file';
    const DOWNLOADED = 'downloaded';
    const PUBLISHED = 'published';
    const GET_CREDITS = 'getcredits';
    const HELP = 'help';
    const INVITE = 'invite';
    const PUBLISH = 'publish';
    const REPORT = 'report';
    const REWARDS = 'rewards';
    const SEARCH = 'search';
    const SEND_CREDITS = 'send';
    const SETTINGS = 'settings';
    const SHOW = 'show';
    const SUBSCRIPTIONS = 'subscriptions';
    const TRANSACTION_HISTORY = 'history';
    const HISTORY = 'user_history';
    const WALLET = 'wallet';
}